# In Class Exercise Lecture 2
Thursday October 24, 2024

## Overview
In this exercise, you will create and import data in the csv format and experiment with the speed of different ways to do matrix multiplication.

## Step 1: Create CSVs
In a text editor of your choice, create two seperate csv files to store the following two matrices:

$$ 
A = \begin{bmatrix}
3 & 7 & 1 & 9 & 2 \\
8 & 4 & 6 & 5 & 3 \\
1 & 2 & 7 & 4 & 8 \\
9 & 6 & 3 & 2 & 5 \\
4 & 8 & 5 & 1 & 7 \\
\end{bmatrix}
$$


$$
B = \begin{bmatrix}
5 & 2 & 9 & 1 & 8 \\
7 & 3 & 4 & 6 & 0 \\
2 & 8 & 1 & 7 & 9 \\
6 & 0 & 5 & 3 & 4 \\
1 & 9 & 8 & 2 & 7 \\
\end{bmatrix}
$$

You can store the data in any format you like. Providing names for the columns is not necessary.

## Step 2: Import CSVs to list
Using the `csv` package, import the two csv files you just created, and format the data into a list of lists, meaning that each element of the list is itself a list which contains the numbers in each row.

```
A = [[row 0], [row 1], ... , [row 4]]
```

In [11]:
# Your code here
import csv

with open('A.csv', 'r') as file:
    reader = csv.reader(file)
    A = [[int(num) for num in row] for row in reader] 

print(A)

with open('B.csv', 'r') as file:
    reader = csv.reader(file)
    B = [[int(num) for num in row] for row in reader] 

print(B)

[[3, 7, 1, 9, 2], [8, 4, 6, 5, 3], [1, 2, 7, 4, 8], [9, 6, 3, 2, 5], [4, 8, 5, 1, 7]]
[[5, 2, 9, 1, 8], [7, 3, 4, 6, 0], [2, 8, 1, 7, 9], [6, 0, 5, 3, 4], [1, 9, 8, 2, 7]]


## Step 3: DIY Matrix Multiplication
Write your own function to calculate $A*B$, using the formatted matrices created in step 2. Do not use `numpy` or any other packages. Recall that the formula for matrix multiplication:

If $A$ is an m x n matrix, and $B$ is an n x p matrix, then $C=AB$ has dimension m x p
$$ c_{ij} = \sum_{k=1}^n a_{ik} b_{kj}$$
for i = 1, ..., m and j = 1, ..., p

https://en.wikipedia.org/wiki/Matrix_multiplication#Definitions

In [41]:
# Your code here

def matrix_multiplication(A, B):
    C = [[0 for i in range(5)]for j in range(5)]

    for i in range(5):
        for j in range(5):
            for k in range(len(B)):
                C[i][j] += int(A[i][k] * B[k][j])
    return C

C = matrix_multiplication(A, B)      
print(C)
    


[[122, 53, 117, 83, 83], [113, 103, 143, 95, 159], [65, 136, 108, 90, 143], [110, 105, 158, 82, 142], [99, 135, 134, 104, 130]]


## Step 4 : Import CSVs to numpy
Using the `csv` package, import the two csv files you just created, and format the data into a `numpy` array

In [33]:
# Your code here
import numpy as np
A = np.array(A)
B = np.array(B)
print(A)
print(B)

[[3 7 1 9 2]
 [8 4 6 5 3]
 [1 2 7 4 8]
 [9 6 3 2 5]
 [4 8 5 1 7]]
[[5 2 9 1 8]
 [7 3 4 6 0]
 [2 8 1 7 9]
 [6 0 5 3 4]
 [1 9 8 2 7]]


## Step 5: Matrix Multiplication with numpy
Compute $A*B$ using the function `numpy.matmul()`.

In [42]:
# Your code here
def np_matmul(A, B):
    return np.matmul(A, B)

np_matmul(A,B)

array([[122,  53, 117,  83,  83],
       [113, 103, 143,  95, 159],
       [ 65, 136, 108,  90, 143],
       [110, 105, 158,  82, 142],
       [ 99, 135, 134, 104, 130]])

## Step 6: Compare Speed of Both Methods
Use the `average_time` function provided below to measure the speed of `numpy.matmul()` and your own method. Ensure `number` $\geq 1000$

In [37]:
import timeit

def average_time(func, *args, number=1000):
    """
    This function measures the average time it takes to execute the provided function.
    
    Parameters:
    - func: The function to time.
    - args: The arguments to pass to the function.
    - number: How many times to run the function (default is 1000).
    
    Returns:
    - Average time taken to run the function.
    """
    # Use timeit with a lambda to pass the function and arguments
    execution_time = timeit.timeit(lambda: func(*args), number=number)
    
    # Return the average time taken
    return execution_time / number



###### Example usage of average_time function
def example_function(x, y):
    return x + y

# Measure the average time for 1000 runs
avg_time = average_time(example_function, 10, 20, number=1000)
print(f"Average execution time: {avg_time:.6f} seconds")

Average execution time: 0.000000 seconds


In [47]:
# Your code here
avg_time_own = average_time(matrix_multiplication, A, B, number=1000)
print(f"Average execution time (own method): {avg_time_own:.6f} seconds")

avg_time_np = average_time(np_matmul, A, B, number=1000)
print(f"Average execution time (numpy method): {avg_time_np:.6f} seconds")

Average execution time (own method): 0.000076 seconds
Average execution time (numpy method): 0.000001 seconds


## Step 7: Create a JSON with the results
Save the results of this test to a JSON file with the following structure:

```
{
	"numpy_multiply": execution time,
    "my_multiply": execution time
}
```
To create the JSON, make a dictionary with the correct structure, and then run the block below to save it.

In [48]:
import json

# Create the dictionary with execution times
execution_times = {"numpy_multiply": avg_time_np, "my_multiply": avg_time_own}

# Save the dictionary to a JSON file
with open('execution_times.json', 'w') as json_file:
    json.dump(execution_times, json_file)

## Step 8: Submit JSON to Canvas
Upload `execution_times.json` to the in class exercise assignment on Canvas